name: CI
on:
  pull_request:
    paths:
      - 'prob_spaces/**'
      - 'tests/**'
      - '.github/workflows/ci.yml'
      - 'pyproject.toml'
      - 'uv.lock'
  workflow_dispatch:
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [  '3.10', '3.11', '3.12', '3.13' ]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - if: matrix.os == 'macos-latest'
        run: brew install swig

      - run: uv python install ${{ matrix.python-version }}
      - run: make
      - run: make test
    continue-on-error: true
